### ISSUE TITLE
[Airbrake] [Production] API error: end of the stream or a document separator is expected at line 4, column 6:     title: #unused          ^

### ISSUE THREAD

**Issue by tbrandle** [bowtie-co/houndstooth-ui#9]
**Airbrake error:** [#7031](https://bowtie.airbrake.io/projects/174928/groups/2429943876571957031)
**Airbrake project:** Houndstooth

**Error type:** `Error`
**Error message:** `` API error: end of the stream or a document separator is expected at line 4, column 6:     title: #unused          ^ ``
**Where:** `<no information>`
**Occurred at:** Mar 07, 2019 16:24:42 UTC
**First seen at:** Mar 07, 2019 16:24:42 UTC
**Occurrences:** 0 (0 since last deploy on Mar 07, 2019 00:23:00 UTC)
**Severity:** `error`

**URL:** [https://houndstooth.cloud/cosapd/sa-midtown-v4/collections/home-slides?ref=master](https://houndstooth.cloud/cosapd/sa-midtown-v4/collections/home-slides?ref=master)
**File:** `https://houndstooth.cloud/static/js/lib/api.js`

**Backtrace:**
```
https://houndstooth.cloud/static/js/lib/api.js:47:in 
/PROJECT_ROOT/dll/dll.vendor.js:62:in r.d.emit
/PROJECT_ROOT/dll/dll.vendor.js:121:in r.value
```

**Comment by 5290charlie** [comment]
Handled in cosapd/sa-midtown-v4 repo by @NickArrasate 

https://www.pivotaltracker.com/story/show/164468810
